steps:
  - label: ":rust: Tests"
    if: build.branch == "main" || build.pull_request.base_branch == "main"
    command: cargo test --locked
    plugins:
      - docker#v5.13.0:
          image: rust:1.94.0
          always-pull: true
