steps:
  - label: ":rust: Tests"
    if: build.branch == "main" || build.pull_request.base_branch == "main"
    command: mise trust && mise run test
    plugins:
      - docker#v5.13.0:
          image: jdxcode/mise:latest
          always-pull: true
          entrypoint: ""
          shell: ["/bin/bash", "-e", "-c"]
