#!/usr/bin/env bash
set -euo pipefail

root=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
"$root/scripts/generate-acp-swift.py"

required_version=2.45.4
required_binary_sha=6aa2b4da95304b343bea12890c59f9655aa428c08b351d57d592cfab4e88a9f1
xcodegen=${XCODEGEN:-xcodegen}
tool_path=$(command -v "$xcodegen" 2>/dev/null || true)
if [[ -z $tool_path ]]; then
  echo "xcodegen is not on PATH. Run: mise install" >&2
  exit 1
fi
actual_binary_sha=$(shasum -a 256 "$tool_path" | awk '{ print $1 }')
if [[ $actual_binary_sha != "$required_binary_sha" ]]; then
  echo "XcodeGen must be the repository-pinned $required_version release binary (found $tool_path)." >&2
  echo "Run mise install, or set XCODEGEN to the pinned binary." >&2
  exit 1
fi

version=$(sed -n 's/^version = "\([^"]*\)"/\1/p' "$root/Cargo.toml" | head -1)
if [[ -z $version ]]; then
  echo "could not derive Kit version from Cargo.toml" >&2
  exit 1
fi
config=$root/macos/Config/Version.xcconfig
temporary=$config.tmp
trap 'rm -f "$temporary"' EXIT
printf '%s\n' \
  '// Generated by scripts/generate-macos-project.sh from Cargo.toml.' \
  "KIT_VERSION = $version" > "$temporary"
if ! cmp -s "$temporary" "$config" 2>/dev/null; then
  mv "$temporary" "$config"
fi

"$xcodegen" generate --spec "$root/macos/project.yml" --project "$root/macos"
