#!/usr/bin/env bash
set -euo pipefail

root=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
"$root/scripts/generate-acp-swift.py"

required_version=2.45.4
if [[ -n ${XCODEGEN:-} ]]; then
  xcodegen=$XCODEGEN
elif [[ -x ${HOME:-}/.local/bin/xcodegen && -f ${HOME:-}/.local/bin/.xcodegen-$required_version-sha256 ]]; then
  xcodegen=${HOME}/.local/bin/xcodegen
else
  xcodegen=xcodegen
fi
required_archive_sha=090ec29491aad50aec10631bf6e62253fed733c50f3aab0f5ffc86bc170bdbef
tool_path=$(command -v "$xcodegen" 2>/dev/null || true)
marker=$(dirname "${tool_path:-/missing}")/.xcodegen-$required_version-sha256
if [[ ! -f $marker || $(cat "$marker") != "$required_archive_sha" ]]; then
  echo "XcodeGen must come from the repository-pinned release archive." >&2
  echo "Run scripts/install-xcodegen.sh and put its destination first in PATH." >&2
  exit 1
fi
actual_version=$($xcodegen --version | awk '/Version:/ { print $2 }')
if [[ $actual_version != "$required_version" ]]; then
  echo "XcodeGen $required_version is required (found ${actual_version:-unknown})" >&2
  echo "Run scripts/install-xcodegen.sh or set XCODEGEN to the pinned binary." >&2
  exit 1
fi

version=$(sed -n 's/^version = "\([^"]*\)"/\1/p' "$root/Cargo.toml" | head -1)
if [[ -z $version ]]; then
  echo "could not derive Kit version from Cargo.toml" >&2
  exit 1
fi
config=$root/macos/Config/Version.xcconfig
temporary=$config.tmp
trap 'rm -f "$temporary"' EXIT
printf '%s\n' \
  '// Generated by scripts/generate-macos-project.sh from Cargo.toml.' \
  "KIT_VERSION = $version" > "$temporary"
if ! cmp -s "$temporary" "$config" 2>/dev/null; then
  mv "$temporary" "$config"
fi

"$xcodegen" generate --spec "$root/macos/project.yml" --project "$root/macos"
